### ISSUE TITLE
Installation fails on yay-installed Sage

### ISSUE THREAD

**Issue by upbqdn** [mwageringel/fgb_sage#2]
I'm trying to install the package into Sage 9.1 and I can't get over the following error:
...
Applying patches.
sh: sage-apply-patches: command not found
Failed to apply patches.

The error pops out when running 'sage setup.py test'.
I'd be happy to fix it on my own and perhaps submit a pull request, but I'm stuck at this.

**Comment by qxwq** [comment]
Similarly to the first issue, I solved this one by using a self-compiled version of Sage. It might be useful to mention this detail in the docs. Now fgb_sage works flawlessly with Sage 9.1. I'd still gladly submit a pull request as regards the docs if there's any will.

**Comment by slel** [comment]
Could you say how the other Sage was installed?
Via a package manager? apt, conda, pacman, rpm, yum?

**Comment by qxwq** [comment]
Sure, I used this package https://www.archlinux.org/packages/community/x86_64/sagemath/, which I installed using the package manager yay on Arch Linux.

**Comment by slel** [comment]
You could maybe reopen this issue and change the title to
"State assumptions on how Sage was installed".
I think a pull request to amend the docs would be nice.
What do you think @mwageringel?

**Comment by slel** [comment]
The first two issues in this repo could be renamed:

- #1 Install instructions fail on apt-installed Sage
- #2 Install instructions fail on yay-installed Sage

**Comment by slel** [comment]
So maybe open a third issue for improving the docs,
and refer to those!

**Comment by mwageringel** [comment]
Thanks for bringing this up. I was not aware of this – apparently the script `sage-apply-patches` is only available in Sage the distribution, but in some packaged versions of Sage it is not. I have added a few words about this to the documentation.

The simplest way to fix this might be to copy that file into this repository.

Regarding #1 , the version of Sage (8.1) might just have been too old.

**Comment by mwageringel** [comment]
This should be fixed now, finally, at least on Arch. Feel free to reopen if there is still a problem on another distribution.
