### ISSUE TITLE
Installation fails on apt-installed Sage

### ISSUE THREAD

**Issue by minionsjay** [mwageringel/fgb_sage#5]
My ubuntu version is 20.04 , use `apt-get` install sagemath-9.0

When executing `sage setup.py` test I get the following error:
Compiling fgb_sage/_fgb_sage_modp.pyx because it changed.
[1/1] Cythonizing fgb_sage/_fgb_sage_modp.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            e = self.monoms + j * self.n_variables
            mon = p_Init(_ring)
            IF PY_LIBMODE == 2:
                p_SetCoeff(mon, nlInit2gmp(self.coeffs[j], one, _ring.cf), _ring)
            ELSE:
                p_SetCoeff(mon, n_Init(self.coeffs[j], _ring.cf), _ring)
                                                           ^
------------------------------------------------------------

fgb_sage/_fgb_sage_modp.pyx:219:60: Cannot assign type 'n_Procs_s *' to 'ring *'
Traceback (most recent call last):
  File "setup.py", line 141, in <module>
    ext_modules = [
  File "setup.py", line 142, in <listcomp>
    cythonize(
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: fgb_sage/_fgb_sage_modp.pyx

**Comment by slel** [comment]
> My ubuntu version is 20.04 , use `apt-get` install sagemath-9.0
> 
> When executing `sage setup.py` test I get the following error:
> ```shell
> Compiling fgb_sage/_fgb_sage_modp.pyx because it changed.
> [1/1] Cythonizing fgb_sage/_fgb_sage_modp.pyx
> ## Error compiling Cython file:
> ## ...
> e = self.monoms + j * self.n_variables
> mon = p_Init(_ring)
> IF PY_LIBMODE == 2:
>   p_SetCoeff(mon, nlInit2gmp(self.coeffs[j], one, _ring.cf), _ring)
> ELSE:
>   p_SetCoeff(mon, n_Init(self.coeffs[j], _ring.cf), _ring)
> 
> fgb_sage/_fgb_sage_modp.pyx:219:60: Cannot assign type 'n_Procs_s *' to 'ring *'
> Traceback (most recent call last):
> File "setup.py", line 141, in ext_modules = [
> File "setup.py", line 142, in cythonize(
> File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
> cythonize_one(*args)
> File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
> raise CompileError(None, pyx_file)
> Cython.Compiler.Errors.CompileError: fgb_sage/_fgb_sage_modp.pyx
> ```

Reporting tip: enclose quoted terminal excerpts within
triple backticks so they get properly rendered.

Install tip: consider installing SageMath via Conda, see
https://doc.sagemath.org/html/en/installation/conda.html
